// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9DrO6riCgyV0txnuXlbtKLyVKPPDwTQA',
    appId: '1:3095398963:web:41557c502319ac3c9fb146',
    messagingSenderId: '3095398963',
    projectId: 'promodeal-a9c6c',
    authDomain: 'promodeal-a9c6c.firebaseapp.com',
    storageBucket: 'promodeal-a9c6c.firebasestorage.app',
    measurementId: 'G-PRQ2EXYMZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzZkCkPFa4RmAL7Z_fcHALkvl_0G89so',
    appId: '1:3095398963:android:52f7f2c8203be8519fb146',
    messagingSenderId: '3095398963',
    projectId: 'promodeal-a9c6c',
    storageBucket: 'promodeal-a9c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_DlSEBJMTKAiEnl8-fsh9Ynnd9JFMFk',
    appId: '1:3095398963:ios:e23472744e6cd47c9fb146',
    messagingSenderId: '3095398963',
    projectId: 'promodeal-a9c6c',
    storageBucket: 'promodeal-a9c6c.firebasestorage.app',
    iosBundleId: 'com.example.promodeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_DlSEBJMTKAiEnl8-fsh9Ynnd9JFMFk',
    appId: '1:3095398963:ios:e23472744e6cd47c9fb146',
    messagingSenderId: '3095398963',
    projectId: 'promodeal-a9c6c',
    storageBucket: 'promodeal-a9c6c.firebasestorage.app',
    iosBundleId: 'com.example.promodeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9DrO6riCgyV0txnuXlbtKLyVKPPDwTQA',
    appId: '1:3095398963:web:652e609ab043a03e9fb146',
    messagingSenderId: '3095398963',
    projectId: 'promodeal-a9c6c',
    authDomain: 'promodeal-a9c6c.firebaseapp.com',
    storageBucket: 'promodeal-a9c6c.firebasestorage.app',
    measurementId: 'G-FK3Y64J92M',
  );
}
